server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: task-manager
          uri: lb://TASK-MANAGER
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/tasks/(?<remaining>.*), /$\{remaining}
